#!/usr/bin/env bash
set -euo pipefail

# install_extentions.sh (intentional spelling for compatibility)
# Glue installer: keep core clean, install custom extensions at deploy time.

REPO_URL=""
REF="main"
DEST_ROOT="${HOME}/.nanobot/extensions-runtime"
MODULES=""
WRITE_ENV="${HOME}/.nanobot/extensions.env"

usage() {
  cat <<'EOF'
Usage:
  scripts/install_extentions.sh --repo <git_url_or_local_path> [options]

Options:
  --repo <value>         Extension source (git URL or local path), required.
  --ref <value>          Git ref to checkout when --repo is a Git URL. Default: main
  --dest <path>          Install root. Default: ~/.nanobot/extensions-runtime
  --modules <list>       Value for NANOBOT_EXTENSION_MODULES (comma-separated)
  --env-file <path>      Output env file path. Default: ~/.nanobot/extensions.env
  -h, --help             Show this help

Examples:
  scripts/install_extentions.sh --repo https://github.com/you/nanobot-extensions.git
  scripts/install_extentions.sh --repo git@github.com:you/nanobot-extensions.git --ref dev
  scripts/install_extentions.sh --repo /opt/nanobot-extensions --modules extensions.reflexio
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_URL="${2:-}"; shift 2 ;;
    --ref) REF="${2:-}"; shift 2 ;;
    --dest) DEST_ROOT="${2:-}"; shift 2 ;;
    --modules) MODULES="${2:-}"; shift 2 ;;
    --env-file) WRITE_ENV="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2 ;;
  esac
done

if [[ -z "$REPO_URL" ]]; then
  echo "Error: --repo is required" >&2
  usage
  exit 2
fi

mkdir -p "$DEST_ROOT"
mkdir -p "$(dirname "$WRITE_ENV")"
SRC_DIR="$DEST_ROOT/src"

is_git_url=false
if [[ "$REPO_URL" =~ ^(https://|git@|ssh://) ]]; then
  is_git_url=true
fi

if $is_git_url; then
  if [[ -d "$SRC_DIR/.git" ]]; then
    echo "[extensions] updating existing repo: $SRC_DIR"
    git -C "$SRC_DIR" fetch --all --tags --prune
    git -C "$SRC_DIR" checkout "$REF"
    git -C "$SRC_DIR" reset --hard "origin/$REF" || true
  else
    rm -rf "$SRC_DIR"
    echo "[extensions] cloning: $REPO_URL -> $SRC_DIR"
    git clone --depth 1 --branch "$REF" "$REPO_URL" "$SRC_DIR"
  fi
else
  if [[ ! -d "$REPO_URL" ]]; then
    echo "Error: local repo path not found: $REPO_URL" >&2
    exit 1
  fi
  rm -rf "$SRC_DIR"
  echo "[extensions] copying local source: $REPO_URL -> $SRC_DIR"
  cp -a "$REPO_URL" "$SRC_DIR"
fi

if [[ ! -d "$SRC_DIR" ]]; then
  echo "Error: source dir missing after fetch: $SRC_DIR" >&2
  exit 1
fi

# Optional editable install when extension repo is a Python package.
if [[ -f "$SRC_DIR/pyproject.toml" || -f "$SRC_DIR/setup.py" ]]; then
  echo "[extensions] python package detected, running editable install"
  python3 -m pip install -e "$SRC_DIR"
fi

AUTO_PROVIDER_FAILOVER=""
if [[ -f "$SRC_DIR/extensions/provider_failover/__init__.py" ]]; then
  AUTO_PROVIDER_FAILOVER="extensions.provider_failover"
fi

# Write runtime env file consumed by shell / service / docker env_file.
{
  echo "# Generated by scripts/install_extentions.sh"
  printf 'export PYTHONPATH="%s:${PYTHONPATH:-}"\n' "$SRC_DIR"
  if [[ -n "$AUTO_PROVIDER_FAILOVER" ]]; then
    printf 'export NANOBOT_PROVIDER_FAILOVER_MODULE="%s"\n' "$AUTO_PROVIDER_FAILOVER"
  fi
  if [[ -n "$MODULES" ]]; then
    printf 'export NANOBOT_EXTENSION_MODULES="%s"\n' "$MODULES"
  fi
} > "$WRITE_ENV"

echo "[extensions] done"
echo "[extensions] source this file before starting nanobot:"
echo "  source $WRITE_ENV"
